# Generated by Django 5.1.1 on 2024-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(error_messages=150)),
                ('contact_methods', models.CharField(max_length=50)),
                ('services', models.ManyToManyField(to='service.service')),
            ],
        ),
    ]
