# Generated by Django 5.1.1 on 2024-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establisment', '0002_establisment_review'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establisment',
            name='services',
            field=models.ManyToManyField(null=True, to='service.service'),
        ),
    ]
