# Generated by Django 5.1.1 on 2024-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establisment', '0003_alter_establisment_services'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establisment',
            name='review',
            field=models.ManyToManyField(null=True, to='review.review'),
        ),
    ]
