# Generated by Django 5.1.1 on 2024-09-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_review'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(to='review.review'),
        ),
    ]
