# Generated by Django 5.1.1 on 2024-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_review_product_review'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(null=True, to='review.review'),
        ),
    ]
