# Generated by Django 5.1.1 on 2024-09-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='estate',
            new_name='state',
        ),
    ]
