# Generated by Django 5.1.1 on 2024-12-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("employee", "0001_initial"),
        ("establisment", "0001_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.DateTimeField()),
                ("estate", models.CharField(max_length=50)),
                ("method", models.CharField(max_length=50)),
                ("event_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.client"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
                (
                    "establisment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="establisment.establisment",
                    ),
                ),
                ("services", models.ManyToManyField(to="service.service")),
            ],
        ),
    ]
