# Generated by Django 5.1.1 on 2024-10-25 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('employee', '0001_initial'),
        ('establisment', '0001_initial'),
        ('schedule', '0001_initial'),
        ('service', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='establisment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establisment.establisment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='service.service'),
        ),
    ]
