# Generated by Django 5.1.1 on 2024-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
