# Generated by Django 5.1.1 on 2024-10-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='accestoken',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='googleid',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='token',
            field=models.CharField(null=True),
        ),
    ]
