# Generated by Django 5.1.1 on 2024-10-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_payment',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
