# Generated by Django 5.1.1 on 2024-11-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='accestoken',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='googleid',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
